### ISSUE TITLE
quartet network with incorrect fields

### ISSUE THREAD

**Issue by cecileane** [crsl4/PhyloNetworks.jl#95] opened 2019-04-28 20:26 UTC
The `Quartet` object contains a field `.qnet`, which is a `QuartetNetwork`. It looks like the calculation of all the data in a `QuartetNetwork` might have a bug, in the list of edges in a quartet subnetwork.

In the example below, we (@RC0515 and I) first read the full network, then the quartet data from file [tableCF.txt](https://github.com/crsl4/PhyloNetworks.jl/files/3125459/tableCF.txt), which we read as a data frame then convert to a `DataCF` object (this is simulated data btw).

```julia
using PhyloNetworks;
net = readTopology("(s17:13.765659574468085,(((s3:10.980829787234043,(s4:8.98882978723404,s5:8.98882978723404)I1:1.992)I2:0.471,(((s6:2.307829787234041,s7:2.307829787234041)I3:4.026,(s8:4.974829787234041,#H24:0.0::0.279)I4:1.3589999999999995)I5:3.6390000000000002,((s9:8.28982978723404,((s10:2.3768297872340414,s11:2.3768297872340414)I6:3.018,(s12:2.6768297872340416,s13:2.6768297872340416)I7:2.718)I8:2.895)I9:0.21000000000000002,((s14:2.8328297872340418,(s15:1.0568297872340429,s16:1.0568297872340429)I10:1.7759999999999998)I11:2.142)#H24:3.5250000000000004::0.721)I12:1.4729999999999999)I13:1.479)I14:1.257,(((s18:5.46082978723404,s19:5.46082978723404)I15:0.5880000000000001,(s20:4.725829787234041,(s21:2.4008297872340414,s22:2.4008297872340414)I16:2.325)I17:1.323)I18:2.682,(s23:8.56582978723404,(s1:4.641829787234041,s2:4.641829787234041)I19:3.9240000000000004)I20:0.165)I21:3.978)I22:1.0568297872340426);");

using CSV
quartetDF = CSV.read("tableCF.txt") # 8855 quartets: because 23 taxa
d = readTableCF(quartetDF)
typeof(d.quartet[1000].qnet) # PhyloNetworks.QuartetNetwork
d.quartet[1000].qnet         # empty at this point
```

We picked quartet # 1000 just at random. This particular quartet shows a problem. Since the 1000th `QuartetNetwork` is empty at this point, we calculate all its data based on our input full network via a call to `topologyQPseudolik!`.

```julia
@time topologyQPseudolik!(net,d) # 30 seconds. score = 2165.7
```

The quartet was updated with information, but it looks like some fields have not been updated. For example, the internal edge length was not updated: how the score of this quartet was calculated without its internal branch length?? Most importantly, some edges are missing. The quartet we picked is of "type 1", that is, equivalent to a tree quartet provided that we adapt the internal edge length. More specifically, it includes 1 reticulation, located on the edge leading to a single taxon ("s1").

```Julia
q = d.quartet[1000].qnet # data is there now
q.which # -1 : still not updated. should be 1 here
unique([d.quartet[i].qnet.which for i in 1:8855]) # [-1]: none of the quartets have an up-to-date ".which"
q.numHybrids # 1: the subnetwork contains 1 reticulation
q.typeHyb    # empty array (length 0): should be of length 1 to give the type of the 1 reticulation
q.hasEdge # array of 24 booleans. 8 are true, 16 are false
q.t1      # -1.0. Should contain the adjusted total length of internal edge
q.split   # [-1,-1,-1,-1]: not yet initialized. Should be [1,1,2,2] because s1,s16 | s18,s23
print(findall(q.hasEdge)) # indices of the 8 true's: [1, 6, 7, 15, 16, 17, 23, 24]
print(q.index) # array of 8 indices: [1, 2, 3, 6, 7, 8, 12, 13]
length(q.edge) # 13
print([e.number for e in q.edge]) # [11,12,13, 25, 28,29,30,31,32, 41,42, 45,46]
```

There is no documentation for the `QuartetNetwork` class... There are some comments in the [code](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/types.jl#L248) but no comments at all for what `edge` is supposed to contain.

The array of edges, `[11,12,13, 25, 28,29,30,31,32, 41,42, 45,46]`, might list the edges that are internal to the quartet. But in fact no. When we look at the plot of the network, we cannot find what these edges are supposed to be.
- it lists all 4 external edges
- it lists most internal edges, not not all. Edges `26,27, 34,40, 44` are internal to the quartet network but missing from the `edge` list.

In the following plot, the 4-taxon set is shown in blue; edges in the `edge` list are shown in brown; edges internal to the quartet but missing from the `edge` list are shown in red (the code to get this plot is shown below).

![missingEdges](https://user-images.githubusercontent.com/9857294/56869665-e5b91b00-69c8-11e9-949c-5d598915ebb4.png)

```Julia
using PhyloPlots;
using RCall;

R"pdf"("missingEdges.pdf", width=8in, height=6in);
R"par"(mar=[0,0,0,0])
res = plot(net, :R, useEdgeLength=true, showTipLabel=false, showEdgeNumber=true, xlim=[1,15.2]);

# number of edges that are missing
missing_num = [26,27, 34,40, 44];
# number of edges that are not missing
not_missing = [11,12,13, 25, 28,29,30,31,32, 41,42, 45,46];

# missing edges are re-drawn in red, not missing edge are re-drawn in brown
cx1, cx2, cy1, cy2 = [[res[i][j] for j in missing_num] for i in 9:12];
mx1, mx2, my1, my2 = [[res[i][j] for j in not_missing] for i in 9:12];
R"arrows"(cx1, cy1, cx2, cy2, col="red", length=0.04, angle=20, lwd=2);
R"arrows"(mx1, my1, mx2, my2, col="brown", length=0.04, angle=20, lwd=2);

# nodes in the 1000th quartet is shown in blue
id1 = findall(in([q.leaf[i].name for i in 1:4]), res[13][:name]) # indices of quartet taxa in res[13]
R"text"(res[13][id1,:x].+0.15, res[13][id1,:y], res[13][id1,:name], col="blue", adj=0);
# show other leaves in black
id2 = findall(!in([q.leaf[i].name for i in 1:4]), res[13][:name])
R"text"(res[13][id2,:x].+0.15,res[13][id2,:y], res[13][id2,:name], col="black", adj=0, cex=0.8);
R"dev.off()";
```

**Comment by crsl4** [comment] 2019-05-01 14:11
The tests `test_calculateExpCF.jl` and `test_calculateExpCF2.jl` are meant to check if the attributes in the `QuartetNetwork` are correctly updated, but these tests do not call `snaq` or `topologyQPseudolik!`. These tests call the specific internal functions, so maybe attributes are only updated internally. I will check!

**Comment by crsl4** [comment] 2019-05-01 15:43
OK! More information:

- Regarding the missing edges, the `QuartetNetwork` has 13 edges in `q.edge`: `[11,12,13, 25, 28,29,30,31,32, 41,42, 45,46]`, with 4 apparently missing edges (in red in `plot.png`): `26,27, 34,40, 44`. These 4 missing edges are not internal edges, and they are combined into the existing external edges. That is, the external edge 25 "swallows" edges 26 and 27 into just one external edge with number 25 (new 25 = old 25 +26+27). Similarly, edge 32 swallows edges 34 and 40 into one external edge denoted 32. Finally, edge 42 swallows edge 44 into one external edge numbered 42

- Regarding the attributes, all updated attributes are done in a deep copy inside `calculateExpCFAll!`, and only `q.qnet.expCF` is updated at the end, see [code](https://github.com/crsl4/PhyloNetworks.jl/blob/8cd253360f9282de5860ef6eaff0a0392b991785/src/pseudolik.jl#L1336).
This is why all attributes are empty. However, `q.expCF` should be updated (see [code](https://github.com/crsl4/PhyloNetworks.jl/blob/8cd253360f9282de5860ef6eaff0a0392b991785/src/pseudolik.jl#L1338)):
```julia
julia> q.expCF
3-element Array{Float64,1}:
 0.2826312346959719
 0.2826312346959719
 0.4347375306080562
```
We can modify the code so that all attributes are updated [here](https://github.com/crsl4/PhyloNetworks.jl/blob/8cd253360f9282de5860ef6eaff0a0392b991785/src/pseudolik.jl#L1338).

**Things that are still unclear:**

- The network `net` has 23 identifiable edges (see `plot.png`): `[31,6,5,9,12,13,30,29,22,11,21,17,20,28,27,26,34,39,38,40,46,45,44]`, and thus the vector with parameters to optimize `net.ht` has length 24: 1 gamma + 23 identifiable edges. The order in which these edges appear is not known, as `net.ht` and `net.index` (indices in net.node and net.edge) are returned empty after the optimization. The quartet network has `q.hasEdge` with length 24, with booleans identifying if each of the parameters to optimize (`net.ht`) are in this `QuartetNetwork`. There are 8 true's:
```julia
print(q.index) # array of 8 indices: [1, 2, 3, 6, 7, 8, 12, 13]
[e.number for e in q.edge[q.index]] # [11, 12, 13, 29, 30, 31, 45, 46]
```
Note that there should be 9 true's in `q.index`, with edge 28 missing. This is potentially a bug!

- I will look into the internal functions (see `test_calculateExpCF2.jl`) for this quartet to see that internally the attributes are correct. However, when I try the code below, nothing happens for minutes:
```
using PhyloNetworks;
net = readTopology("(s17:13.765659574468085,(((s3:10.980829787234043,(s4:8.98882978723404,s5:8.98882978723404)I1:1.992)I2:0.471,(((s6:2.307829787234041,s7:2.307829787234041)I3:4.026,(s8:4.974829787234041,#H24:0.0::0.279)I4:1.3589999999999995)I5:3.6390000000000002,((s9:8.28982978723404,((s10:2.3768297872340414,s11:2.3768297872340414)I6:3.018,(s12:2.6768297872340416,s13:2.6768297872340416)I7:2.718)I8:2.895)I9:0.21000000000000002,((s14:2.8328297872340418,(s15:1.0568297872340429,s16:1.0568297872340429)I10:1.7759999999999998)I11:2.142)#H24:3.5250000000000004::0.721)I12:1.4729999999999999)I13:1.479)I14:1.257,(((s18:5.46082978723404,s19:5.46082978723404)I15:0.5880000000000001,(s20:4.725829787234041,(s21:2.4008297872340414,s22:2.4008297872340414)I16:2.325)I17:1.323)I18:2.682,(s23:8.56582978723404,(s1:4.641829787234041,s2:4.641829787234041)I19:3.9240000000000004)I20:0.165)I21:3.978)I22:1.0568297872340426);");

q1 = Quartet(1,["s1", "s16", "s18", "s23"],[0.29605,0.305921,0.398026]) ## CFs copied from tableCF.txt
qnet = PhyloNetworks.extractQuartet!(net,q1) ##taking forever!
```

**Comment by crsl4** [comment] 2019-05-01 16:28
One minor addition: I am able to run the internal functions now. I just had to update all the network attributes for level-1, before calling `extractQuartet!`:
```
net0 = readTopology("(s17:13.765659574468085,(((s3:10.980829787234043,(s4:8.98882978723404,s5:8.98882978723404)I1:1.992)I2:0.471,(((s6:2.307829787234041,s7:2.307829787234041)I3:4.026,(s8:4.974829787234041,#H24:0.0::0.279)I4:1.3589999999999995)I5:3.6390000000000002,((s9:8.28982978723404,((s10:2.3768297872340414,s11:2.3768297872340414)I6:3.018,(s12:2.6768297872340416,s13:2.6768297872340416)I7:2.718)I8:2.895)I9:0.21000000000000002,((s14:2.8328297872340418,(s15:1.0568297872340429,s16:1.0568297872340429)I10:1.7759999999999998)I11:2.142)#H24:3.5250000000000004::0.721)I12:1.4729999999999999)I13:1.479)I14:1.257,(((s18:5.46082978723404,s19:5.46082978723404)I15:0.5880000000000001,(s20:4.725829787234041,(s21:2.4008297872340414,s22:2.4008297872340414)I16:2.325)I17:1.323)I18:2.682,(s23:8.56582978723404,(s1:4.641829787234041,s2:4.641829787234041)I19:3.9240000000000004)I20:0.165)I21:3.978)I22:1.0568297872340426);");
net = readTopologyLevel1(writeTopology(net0))
q1 = Quartet(1,["s1", "s16", "s18", "s23"],[0.29605,0.305921,0.398026]) ## CFs copied from tableCF.txt
qnet = PhyloNetworks.extractQuartet!(net,q1)
```
I will keep looking into this!

**Comment by cecileane** [comment] 2019-05-01 17:32
Thanks @crsl4 for these explanations! It looks like it would be more efficient to modify the `QuartetNetwork` in place, because with many many networks, much time could be saved.

By the way, the current code does this to update the current Q network's expected CRs:
```julia
q.qnet.expCF = qnet.expCF
```
It might be more efficient to do this, to modify the current memory in place, if the current array `q.qnet.expCF` has the correct size (3):
```julia
q.qnet.expCF[:] = qnet.expCF
```
but it would be just easier and more efficient to avoid the deep-copying.

**Comment by cecileane** [comment] 2019-05-01 18:11
- It would be really helpful to have a docstring for this data type, for example to explain that the `edge` list is supposed to list all the edges in the quartet subnetwork, except that edges external (within the 4-taxon network) are represented by a single edge: the one edge that is external in the full network.
Docstrings can be added to fields within a type: as explained in the Julia [manual for doc](https://docs.julialang.org/en/v1/manual/documentation/index.html#Types-1). Example copy-pasted (and modified) from there:
```julia
"""
    T

general doc for `T`
"""
struct T
    "doc for field x"
    x
    "doc for T.y"
    y
end
```
- The other issue is strange indeed! good catch.

**Comment by crsl4** [comment] 2019-05-01 18:17
Regarding the attributes in `QuartetNetwork`, I think that there is no bug.
I will look at this quartet with the internal functions (following `test_calculateExpCF.jl`):
```julia
using PhyloNetworks;
net0 = readTopology("(s17:13.765659574468085,(((s3:10.980829787234043,(s4:8.98882978723404,s5:8.98882978723404)I1:1.992)I2:0.471,(((s6:2.307829787234041,s7:2.307829787234041)I3:4.026,(s8:4.974829787234041,#H24:0.0::0.279)I4:1.3589999999999995)I5:3.6390000000000002,((s9:8.28982978723404,((s10:2.3768297872340414,s11:2.3768297872340414)I6:3.018,(s12:2.6768297872340416,s13:2.6768297872340416)I7:2.718)I8:2.895)I9:0.21000000000000002,((s14:2.8328297872340418,(s15:1.0568297872340429,s16:1.0568297872340429)I10:1.7759999999999998)I11:2.142)#H24:3.5250000000000004::0.721)I12:1.4729999999999999)I13:1.479)I14:1.257,(((s18:5.46082978723404,s19:5.46082978723404)I15:0.5880000000000001,(s20:4.725829787234041,(s21:2.4008297872340414,s22:2.4008297872340414)I16:2.325)I17:1.323)I18:2.682,(s23:8.56582978723404,(s1:4.641829787234041,s2:4.641829787234041)I19:3.9240000000000004)I20:0.165)I21:3.978)I22:1.0568297872340426);");

net = readTopologyLevel1(writeTopology(net0))


q1 = Quartet(1,["s1", "s16", "s18", "s23"],[0.29605,0.305921,0.398026]) ## CFs copied from tableCF.txt
qnet = PhyloNetworks.extractQuartet!(net,q1) 
PhyloNetworks.identifyQuartet!(qnet)
qnet.which ## 1, correct!
qnet.hybrid[1].k ## 2, correct!
qnet.hybrid[1].typeHyb ## 1, correct!
qnet.typeHyb ## [1], correct!

PhyloNetworks.eliminateHybridization!(qnet)
qnet.t1 ##0.165
```
The internal edge is only edge 45, with length 0.165 (from `printEdges(net)`, not shown).

```julia
PhyloNetworks.updateSplit!(qnet)
qnet.split ## [2,2,1,1]
qnet.quartetTaxon
##4-element Array{String,1}:
## "s1" 
## "s16"
## "s18"
## "s23"
[n.name for n in qnet.leaf]
##4-element Array{String,1}:
## "s16"
## "s18"
## "s23"
## "s1"
```
I expected `qnet.split` to be `[1,2,2,1]`, because we have s1,s23 | s16,s18 and I thought it was compared to `qnet.quartetTaxon` (s1,s16,s18,s23), but no, it is compared to the order in `qnet.leaf` (s16,s18,s23,s1). Cecile says "Should be [1,1,2,2] because s1,s16 | s18,s23", but I think it is s1,s23 | s16,s18. So, `[2,2,1,1]` is correct.

```julia
PhyloNetworks.updateFormula!(qnet)
qnet.formula ##[2,2,1] = [minor, minor, major]
```
This is correct, but how is this happening? The order in `qnet.split` depends on the order in `qnet.leaf` (s16,s18,s23,s1). If `qnet.formula` uses this same order, then we would have: 
s16,s18|s23,s1 = major; s16,s23|s18,s1 = minor; s16,s1|s18,s23 = minor => `[1,2,2]`, which is not what we get. We get the correct formula order (minor, minor, major) based on the order in which we see the taxa in the CF table (in this case: s1,s16,s18,s23), so that we have 
s1,s16|s18,s23 = minor, s1,s18|s16,s23 = minor, s1,s23|s16,s18 = major => `[2,2,1]`.

So, the order is correct in spite of `qnet.split` using the order in `qnet.leaf`, and `qnet.formula` relying on `qnet.split`. How?

Let's trace what `updateFormula!` is doing:
```julia
qnet.quartetTaxon[1] ##s1
qnet.quartetTaxon[2] ##s16
i=2
tx1,tx2 = PhyloNetworks.whichLeaves(qnet,qnet.quartetTaxon[1],qnet.quartetTaxon[i], qnet.leaf[1], qnet.leaf[2], qnet.leaf[3], qnet.leaf[4]) ## 4,1 => s1->leaf4, s16->leaf1
```
So, this function is actually going back to the order we see in `qnet.quartetTaxon`, the same order in which we see the taxa in the CF table (in this case: s1,s16,s18,s23). So, `qnet.formula` does match what it should.

Thus, after running `topologyQPseudolik!` we do not have these attributes updated (only `q.expCF`) because all these attributes are updated in a deep copy. But we can change this behavior in the [code](https://github.com/crsl4/PhyloNetworks.jl/blob/736e2c8fecc2de76a6757cd6a9526d357f62da8a/src/pseudolik.jl#L1338).

**One thing missing on my plate:** why is edge 28 not included in `q.index`? This does not affect the result, because this edge is part of a hybridization cycle involving two nodes, so it is ultimately removed. I believe this was an intended behavior, but I have to make sure.

**Comment by crsl4** [comment] 2019-05-01 18:31
Thanks @cecileane . Yes, docstrings are needed for this type. I will work on this.

Also, I remember that there was a reason why I did not want to modify the `QuartetNetwork` objects stored in the `DataCF` object directly.  I don't remember many details (I have to look at the code), but I think it has to do with the connection to the original edges in `net`.
I know that the internal functions (like `identifyQuartet!`, `updateSplit!`, etc) needed to update the attributes destroy certain aspects of the `QuartetNetwork` object. For example, they merge edges together or get rid of type 1 hybridizations. We wanted to keep the original `QuartetNetwork` stored in `DataCF` with all the identifiable edges to be able to determine if this object had been changed or not after a certain optimization (see [here](https://github.com/crsl4/PhyloNetworks.jl/blob/736e2c8fecc2de76a6757cd6a9526d357f62da8a/src/pseudolik.jl#L1288)).
I think that if we make changes on the `QuartetNetwork` directly, we lose the one-to-one correspondence of edges in the network `net` and the edges in the stored `QuartetNetwork` objects.

I do not know much about modifying memory in place `q.qnet.expCF[:] = qnet.expCF`, but it sounds like something we can certainly do.

**Comment by cecileane** [comment] 2019-05-01 18:48
So, would a deep-copy not also modify the full network? `q.edge` is empty at first, and that's what gets deep-copied. Isn't there another deep-copy when the `.node` or `.edge` lists are initialized at first?

**Comment by crsl4** [comment] 2019-05-01 20:15
Not sure if I follow. 
Following [here](https://github.com/crsl4/PhyloNetworks.jl/blob/736e2c8fecc2de76a6757cd6a9526d357f62da8a/src/pseudolik.jl#L1331):

1. First, all `QuartetNetwork` objects are created with `extractQuartet!(net,d)`, where `net` is the `HybridNetwork` and `d` is the `DataCF`. 

2. After this call, the vector `d.quartet` has all the `Quartet` objects, each with a `QuartetNetwork` object `q.qnet`. These `QuartetNetwork` objects do have `.node` and `.edge` attributes, but they do not have the other attributes (`.split, .formula, .typeHyb,...`) updated. To update these attributes, we need to call `calculateExpCFAll!(q.qnet);` on all `q` in `d.quartet`. However, we create a deepcopy first `qnet = deepcopy(q.qnet)` and then call `calculateExpCFAll!(qnet)`, because the function `calculateExpCFAll!` will modify the `QuartetNetwork` object directly. 

I remember we do not want to do this, but I could be wrong. I think that functions like [this](https://github.com/crsl4/PhyloNetworks.jl/blob/736e2c8fecc2de76a6757cd6a9526d357f62da8a/src/pseudolik.jl#L1288) do need the `QuartetNetwork` to be un-modified (not merged edges, e.g.).
If we call `calculateExpCFAll!` on the `q.qnet` directly, we will be merging edges, etc., which potentially could interfere with `update!`, or other functions.

**Comment by crsl4** [comment] 2019-05-01 21:07
> **One thing missing on my plate:** why is edge 28 not included in `q.index`? This does not affect the result, because this edge is part of a hybridization cycle involving two nodes, so it is ultimately removed. I believe this was an intended behavior, but I have to make sure.

This is actually not a bug either, but again, due to misleading/confusing/non-existent documentation for `QuartetNetwork` object.

The original network has 23 identifiable edges (see `plot.png` to match the edge numbers):
```julia
using PhyloNetworks;
net0 = readTopology("(s17:13.765659574468085,(((s3:10.980829787234043,(s4:8.98882978723404,s5:8.98882978723404)I1:1.992)I2:0.471,(((s6:2.307829787234041,s7:2.307829787234041)I3:4.026,(s8:4.974829787234041,#H24:0.0::0.279)I4:1.3589999999999995)I5:3.6390000000000002,((s9:8.28982978723404,((s10:2.3768297872340414,s11:2.3768297872340414)I6:3.018,(s12:2.6768297872340416,s13:2.6768297872340416)I7:2.718)I8:2.895)I9:0.21000000000000002,((s14:2.8328297872340418,(s15:1.0568297872340429,s16:1.0568297872340429)I10:1.7759999999999998)I11:2.142)#H24:3.5250000000000004::0.721)I12:1.4729999999999999)I13:1.479)I14:1.257,(((s18:5.46082978723404,s19:5.46082978723404)I15:0.5880000000000001,(s20:4.725829787234041,(s21:2.4008297872340414,s22:2.4008297872340414)I16:2.325)I17:1.323)I18:2.682,(s23:8.56582978723404,(s1:4.641829787234041,s2:4.641829787234041)I19:3.9240000000000004)I20:0.165)I21:3.978)I22:1.0568297872340426);");

net = readTopologyLevel1(writeTopology(net0))
sum([e.istIdentifiable for e in net.edge]) ## 23 identifiable edges in net
idedges = [ee.number for ee in net.edge[[e.istIdentifiable for e in net.edge]]]
print(idedges)
## [5, 6, 9, 11, 12, 13, 17, 20, 21, 22, 26, 27, 28, 29, 30, 31, 34, 38, 39, 40, 44, 45, 46]
```
When we extract the `QuartetNetwork` object, there are only 7 identifiable edges:
```julia
q1 = Quartet(1,["s1", "s16", "s18", "s23"],[0.29605,0.305921,0.398026]) ## CFs copied from tableCF.txt
qnet = PhyloNetworks.extractQuartet!(net,q1) 
length(qnet.hasEdge) ## 24 = 1 gamma + 23 identifiable edges
sum(qnet.hasEdge) ## 8 = 1 gamma + 7 identifiable edges in qnet
## the 7 identifiable edges in qnet must be: [12,13,29,30,31,46,45]
## and they are:
print(idedges[qnet.hasEdge[2:end]]) ##[12, 13, 29, 30, 31, 45, 46]
## so this is correct!
```
This is because the two hybrid edges (edge 11 and edge 28) are not considered identifiable in `QuartetNetwork` anymore because the child of the hybrid node is a leaf.

Now, is `qnet.index` correct?
```
length(qnet.index) ## 8
print([e.number for e in qnet.edge[qnet.index[2:end]]]) ##[12, 13, 29, 30, 31, 45, 46]
```
This looks correct, but the first entry is 1.
Who is the first index in `qnet.index` then? It corresponds to the hybridization, which is present in `qnet`, and it corresponds to the index in `qnet.edge` for the minor hybrid edge:
```
qnet.edge[qnet.index[1]].number ## 11 = minor hybrid edge
```

Again, headaches could have been avoided had I accurately documented the `QuartetNetwork` type. I will do that next, and I think we can close this issue, if you agree @cecileane .

**Comment by cecileane** [comment] 2019-05-01 23:30
I still don't get why `qnet` should not be changed. When it's created in the first place, there's already a deep copy of the full network, see the code here for [`QuartetNetwork(net)`](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/types.jl#L270).

If the edges and nodes need to be recomputed for a given quartet subnetwork, it would seem more efficient to re-do a deep copy of the full list of edges and nodes from the full network, but otherwise update the other elements in the current `QuartetNetwork` object.

If the full network is unchanged, however (just the branch lengths or γ's), there would not even be a need to re-calculate the edges & nodes in the quartet subnetwork.

**Comment by cecileane** [comment] 2019-05-01 23:34
> the two hybrid edges (edge 11 and edge 28) are not considered identifiable in QuartetNetwork anymore because the child of the hybrid node is a leaf.

Here, I disagree about ignoring edge 28. If its branch length is identifiable from the full data set, then it's important to know whether 28 is in the quartet subnetwork. From this single quartet, one might not be able to identify the branch length of edge 28 separately from another parameter. But this branch length could still be affecting the likelihood of that 4-taxon set. The fact that it's not identifiable from the single quartet does *not* mean that it doesn't affect the likelihood of that quartet.

**Comment by cecileane** [comment] 2019-05-01 23:44
> I think that if we make changes on the QuartetNetwork directly, we lose the one-to-one correspondence of edges in the network net and the edges in the stored QuartetNetwork objects.

I trust you that it's a delicate & difficult thing to refactor. I think that for now, a good change would be to write up docstrings explaining what a `QuartetNetwork` is supposed to contain, and a docstring for an internal function or for the `QuartetNetwork` type itself, saying that many fields in a `QuartetNetwork` object might not be updated, because they were updated in a deep copy during the calculation of expected CFs.

**Comment by crsl4** [comment] 2019-05-02 13:49
> I still don't get why `qnet` should not be changed. When it's created in the first place, there's already a deep copy of the full network, see the code here for [`QuartetNetwork(net)`](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/types.jl#L270).
> 
> If the edges and nodes need to be recomputed for a given quartet subnetwork, it would seem more efficient to re-do a deep copy of the full list of edges and nodes from the full network, but otherwise update the other elements in the current `QuartetNetwork` object.
> 
> If the full network is unchanged, however (just the branch lengths or γ's), there would not even be a need to re-calculate the edges & nodes in the quartet subnetwork.

The problem is that the functions that update the other attributes (e.g. `.split, .expCF,...`) merge edges in the `qnet`. 
And to update the other elements in the current `QuartetNetwork`, we need to have the original `qnet` version (without merged edges, removed redundant cycles, etc...) because after optimization of branch lengths in the full network, this `qnet` has branch lengths updated. But the edges need to be there for the update to happen.

So, the process is:
1. Deep copy of full network is done to create `q.qnet` for `Quartet` `q`. This `QuartetNetwork` object has only 4 leaves now, but does not have merged edges (the identifiable ones) so that we can correspond to the edges in `net`. This `QuartetNetwork` does not have other attributes updated.
2. For the current set of branch lengths and gammas, we can update the attributes in `q.qnet` to compute the expected CF. The functions that do this will "destroy" the `QuartetNetwork` object by merging edges, removing nodes, etc... So, we do this process in `qnet=deepcopy(q.qnet), and at the end, only update `q.qnet.expCF`.
3. After we optimize branch lengths in the full network, we want to update the branch lengths in `q.qnet`. The edges need to be there (which is why we do not want to modify this `QuartetNetwork` object by merging edges), and we do not do a deep-copy of the full network again. We only change the values of branch lengths and gammas in `q.qnet`, and we can re-calculate the expCF by creating a deep copy `qnet=deepcopy(q.qnet)` and run the other functions (which merge edges, etc) to get the expCF.

There might be a more efficient way to do this, for sure.

I will update the documentation!

**Comment by crsl4** [comment] 2019-05-31 15:28
I will close this issue because only thing missing is my documentation as the fields are not really incorrect (only documentation is lacking).

**Closed by crsl4** 2019-05-31 15:28 UTC

**Comment by crsl4** [comment] 2020-07-19 20:59
@cecileane Could I use this example (short version) for the docstring of `QuartetNetwork` ?

**Comment by cecileane** [comment] 2020-08-03 16:10
absolutely! the quartet CF data is already in the package, so it could be easily used as an example for the docstring.
